//
//MIT License
//Copyright(c) 2020 Futurewei Cloud
//
//Permission is hereby granted,
//free of charge, to any person obtaining a copy of this software and associated documentation files(the "Software"), to deal in the Software without restriction,
//including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and / or sell copies of the Software, and to permit persons
//to whom the Software is furnished to do so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
//WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: neighbor.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NeighborType int32

const (
	NeighborType_L2 NeighborType = 0 // the default type
	NeighborType_L3 NeighborType = 1
)

// Enum value maps for NeighborType.
var (
	NeighborType_name = map[int32]string{
		0: "L2",
		1: "L3",
	}
	NeighborType_value = map[string]int32{
		"L2": 0,
		"L3": 1,
	}
)

func (x NeighborType) Enum() *NeighborType {
	p := new(NeighborType)
	*p = x
	return p
}

func (x NeighborType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NeighborType) Descriptor() protoreflect.EnumDescriptor {
	return file_neighbor_proto_enumTypes[0].Descriptor()
}

func (NeighborType) Type() protoreflect.EnumType {
	return &file_neighbor_proto_enumTypes[0]
}

func (x NeighborType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NeighborType.Descriptor instead.
func (NeighborType) EnumDescriptor() ([]byte, []int) {
	return file_neighbor_proto_rawDescGZIP(), []int{0}
}

type NeighborConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RevisionNumber    uint32                                    `protobuf:"varint,1,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	RequestId         string                                    `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Id                string                                    `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	UpdateType        UpdateType                                `protobuf:"varint,4,opt,name=update_type,json=updateType,proto3,enum=alcor.schema.UpdateType" json:"update_type,omitempty"` // DELTA (default) or FULL
	VpcId             string                                    `protobuf:"bytes,5,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	Name              string                                    `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	MacAddress        string                                    `protobuf:"bytes,7,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	HostIpAddress     string                                    `protobuf:"bytes,8,opt,name=host_ip_address,json=hostIpAddress,proto3" json:"host_ip_address,omitempty"`
	FixedIps          []*NeighborConfiguration_FixedIp          `protobuf:"bytes,9,rep,name=fixed_ips,json=fixedIps,proto3" json:"fixed_ips,omitempty"`
	AllowAddressPairs []*NeighborConfiguration_AllowAddressPair `protobuf:"bytes,10,rep,name=allow_address_pairs,json=allowAddressPairs,proto3" json:"allow_address_pairs,omitempty"`
}

func (x *NeighborConfiguration) Reset() {
	*x = NeighborConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighbor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NeighborConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborConfiguration) ProtoMessage() {}

func (x *NeighborConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_neighbor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborConfiguration.ProtoReflect.Descriptor instead.
func (*NeighborConfiguration) Descriptor() ([]byte, []int) {
	return file_neighbor_proto_rawDescGZIP(), []int{0}
}

func (x *NeighborConfiguration) GetRevisionNumber() uint32 {
	if x != nil {
		return x.RevisionNumber
	}
	return 0
}

func (x *NeighborConfiguration) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NeighborConfiguration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NeighborConfiguration) GetUpdateType() UpdateType {
	if x != nil {
		return x.UpdateType
	}
	return UpdateType_DELTA
}

func (x *NeighborConfiguration) GetVpcId() string {
	if x != nil {
		return x.VpcId
	}
	return ""
}

func (x *NeighborConfiguration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NeighborConfiguration) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NeighborConfiguration) GetHostIpAddress() string {
	if x != nil {
		return x.HostIpAddress
	}
	return ""
}

func (x *NeighborConfiguration) GetFixedIps() []*NeighborConfiguration_FixedIp {
	if x != nil {
		return x.FixedIps
	}
	return nil
}

func (x *NeighborConfiguration) GetAllowAddressPairs() []*NeighborConfiguration_AllowAddressPair {
	if x != nil {
		return x.AllowAddressPairs
	}
	return nil
}

type NeighborState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationType OperationType          `protobuf:"varint,1,opt,name=operation_type,json=operationType,proto3,enum=alcor.schema.OperationType" json:"operation_type,omitempty"`
	Configuration *NeighborConfiguration `protobuf:"bytes,2,opt,name=configuration,proto3" json:"configuration,omitempty"`
}

func (x *NeighborState) Reset() {
	*x = NeighborState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighbor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NeighborState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborState) ProtoMessage() {}

func (x *NeighborState) ProtoReflect() protoreflect.Message {
	mi := &file_neighbor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborState.ProtoReflect.Descriptor instead.
func (*NeighborState) Descriptor() ([]byte, []int) {
	return file_neighbor_proto_rawDescGZIP(), []int{1}
}

func (x *NeighborState) GetOperationType() OperationType {
	if x != nil {
		return x.OperationType
	}
	return OperationType_INFO
}

func (x *NeighborState) GetConfiguration() *NeighborConfiguration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type NeighborConfiguration_FixedIp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NeighborType NeighborType `protobuf:"varint,1,opt,name=neighbor_type,json=neighborType,proto3,enum=alcor.schema.NeighborType" json:"neighbor_type,omitempty"`
	SubnetId     string       `protobuf:"bytes,2,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	IpAddress    string       `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
}

func (x *NeighborConfiguration_FixedIp) Reset() {
	*x = NeighborConfiguration_FixedIp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighbor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NeighborConfiguration_FixedIp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborConfiguration_FixedIp) ProtoMessage() {}

func (x *NeighborConfiguration_FixedIp) ProtoReflect() protoreflect.Message {
	mi := &file_neighbor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborConfiguration_FixedIp.ProtoReflect.Descriptor instead.
func (*NeighborConfiguration_FixedIp) Descriptor() ([]byte, []int) {
	return file_neighbor_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NeighborConfiguration_FixedIp) GetNeighborType() NeighborType {
	if x != nil {
		return x.NeighborType
	}
	return NeighborType_L2
}

func (x *NeighborConfiguration_FixedIp) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *NeighborConfiguration_FixedIp) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type NeighborConfiguration_AllowAddressPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpAddress  string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	MacAddress string `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
}

func (x *NeighborConfiguration_AllowAddressPair) Reset() {
	*x = NeighborConfiguration_AllowAddressPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighbor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NeighborConfiguration_AllowAddressPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborConfiguration_AllowAddressPair) ProtoMessage() {}

func (x *NeighborConfiguration_AllowAddressPair) ProtoReflect() protoreflect.Message {
	mi := &file_neighbor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborConfiguration_AllowAddressPair.ProtoReflect.Descriptor instead.
func (*NeighborConfiguration_AllowAddressPair) Descriptor() ([]byte, []int) {
	return file_neighbor_proto_rawDescGZIP(), []int{0, 1}
}

func (x *NeighborConfiguration_AllowAddressPair) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NeighborConfiguration_AllowAddressPair) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

var File_neighbor_proto protoreflect.FileDescriptor

var file_neighbor_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x61, 0x6c, 0x63, 0x6f, 0x72, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x1a, 0x0c,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x05, 0x0a,
	0x15, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0e, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x39,
	0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x61, 0x6c, 0x63, 0x6f, 0x72, 0x2e, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x76, 0x70, 0x63,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x70, 0x63, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x70,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x68, 0x6f, 0x73, 0x74, 0x49, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x48, 0x0a,
	0x09, 0x66, 0x69, 0x78, 0x65, 0x64, 0x5f, 0x69, 0x70, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2b, 0x2e, 0x61, 0x6c, 0x63, 0x6f, 0x72, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e,
	0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x78, 0x65, 0x64, 0x49, 0x70, 0x52, 0x08, 0x66,
	0x69, 0x78, 0x65, 0x64, 0x49, 0x70, 0x73, 0x12, 0x64, 0x0a, 0x13, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x61, 0x6c, 0x63, 0x6f, 0x72, 0x2e, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x50, 0x61, 0x69, 0x72, 0x52, 0x11, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x50, 0x61, 0x69, 0x72, 0x73, 0x1a, 0x86, 0x01,
	0x0a, 0x07, 0x46, 0x69, 0x78, 0x65, 0x64, 0x49, 0x70, 0x12, 0x3f, 0x0a, 0x0d, 0x6e, 0x65, 0x69,
	0x67, 0x68, 0x62, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1a, 0x2e, 0x61, 0x6c, 0x63, 0x6f, 0x72, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e,
	0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x6e, 0x65,
	0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x75, 0x62, 0x6e, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x70, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x70, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x52, 0x0a, 0x10, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x50, 0x61, 0x69, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x70,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x63,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x9e, 0x01, 0x0a, 0x0d, 0x4e,
	0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x42, 0x0a, 0x0e,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x6c, 0x63, 0x6f, 0x72, 0x2e, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x49, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x6c, 0x63, 0x6f, 0x72, 0x2e,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x1e, 0x0a, 0x0c, 0x4e,
	0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4c,
	0x32, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x33, 0x10, 0x01, 0x42, 0x4f, 0x0a, 0x1a, 0x63,
	0x6f, 0x6d, 0x2e, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x77, 0x65, 0x69, 0x2e, 0x61, 0x6c, 0x63,
	0x6f, 0x72, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x42, 0x08, 0x4e, 0x65, 0x69, 0x67, 0x68,
	0x62, 0x6f, 0x72, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x77, 0x65, 0x69, 0x2d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f,
	0x61, 0x6c, 0x63, 0x6f, 0x72, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_neighbor_proto_rawDescOnce sync.Once
	file_neighbor_proto_rawDescData = file_neighbor_proto_rawDesc
)

func file_neighbor_proto_rawDescGZIP() []byte {
	file_neighbor_proto_rawDescOnce.Do(func() {
		file_neighbor_proto_rawDescData = protoimpl.X.CompressGZIP(file_neighbor_proto_rawDescData)
	})
	return file_neighbor_proto_rawDescData
}

var file_neighbor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_neighbor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_neighbor_proto_goTypes = []interface{}{
	(NeighborType)(0),                              // 0: alcor.schema.NeighborType
	(*NeighborConfiguration)(nil),                  // 1: alcor.schema.NeighborConfiguration
	(*NeighborState)(nil),                          // 2: alcor.schema.NeighborState
	(*NeighborConfiguration_FixedIp)(nil),          // 3: alcor.schema.NeighborConfiguration.FixedIp
	(*NeighborConfiguration_AllowAddressPair)(nil), // 4: alcor.schema.NeighborConfiguration.AllowAddressPair
	(UpdateType)(0),                                // 5: alcor.schema.UpdateType
	(OperationType)(0),                             // 6: alcor.schema.OperationType
}
var file_neighbor_proto_depIdxs = []int32{
	5, // 0: alcor.schema.NeighborConfiguration.update_type:type_name -> alcor.schema.UpdateType
	3, // 1: alcor.schema.NeighborConfiguration.fixed_ips:type_name -> alcor.schema.NeighborConfiguration.FixedIp
	4, // 2: alcor.schema.NeighborConfiguration.allow_address_pairs:type_name -> alcor.schema.NeighborConfiguration.AllowAddressPair
	6, // 3: alcor.schema.NeighborState.operation_type:type_name -> alcor.schema.OperationType
	1, // 4: alcor.schema.NeighborState.configuration:type_name -> alcor.schema.NeighborConfiguration
	0, // 5: alcor.schema.NeighborConfiguration.FixedIp.neighbor_type:type_name -> alcor.schema.NeighborType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_neighbor_proto_init() }
func file_neighbor_proto_init() {
	if File_neighbor_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_neighbor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NeighborConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighbor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NeighborState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighbor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NeighborConfiguration_FixedIp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighbor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NeighborConfiguration_AllowAddressPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_neighbor_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_neighbor_proto_goTypes,
		DependencyIndexes: file_neighbor_proto_depIdxs,
		EnumInfos:         file_neighbor_proto_enumTypes,
		MessageInfos:      file_neighbor_proto_msgTypes,
	}.Build()
	File_neighbor_proto = out.File
	file_neighbor_proto_rawDesc = nil
	file_neighbor_proto_goTypes = nil
	file_neighbor_proto_depIdxs = nil
}
